### ISSUE TITLE
This code does not work

### ISSUE THREAD

**Issue by Zuowei-Wang** [ManiadisG/DivClust#4]
I followed the documentation strictly according to the virtual environment in anaconda, but in the end the code shows that it can't run, suggesting that there is no resource module, I'm running it in windows 11 pycharm

**Comment by ManiadisG** [comment]
I think this issue is related to Windows, not the code itself.

I believe that in Linux systems the resource module is included in python environments by default. You can try installing the resource module manually (pip install resource) or removing the offending parts of the code (they are in main.py), but beyond that I'm afraid I can't help very much, I haven't got any experience setting up python environments in Windows.
